package utils;

import android.content.Context;
import android.graphics.Point;
import android.view.Display;
import android.view.WindowManager;

import com.and.zmain_life.R;
import com.and.zmain_life.utils.RandomUtil;

import java.util.ArrayList;
import java.util.Random;

public  class ZUtil {

    public static Context mContext;

    public  static void  initContext(Context xContext){
        mContext = xContext;
    }



    public static int getRealScreenWidth() {
        Point realSize = new Point();
        Display realDisplay = ((WindowManager) (mContext.getSystemService(Context.WINDOW_SERVICE))).getDefaultDisplay();
        realDisplay.getRealSize(realSize);
        int w_screen = realSize.x;
        return w_screen;
    }


    public static int getRealScreenHeight() {
        Point realSize = new Point();
        Display realDisplay = ((WindowManager) (mContext.getSystemService(Context.WINDOW_SERVICE))).getDefaultDisplay();
        realDisplay.getRealSize(realSize);
        int h_screen = realSize.y;
        return h_screen;
    }




    public static int getSelectedColor(){
   return R.color.SpringGreen;

    }


    public static int getRainbowColor_random(){
      ArrayList<Integer> randomIndex =  RandomUtil.getRandomLengthArr(rainbow_colorList.length);
        Random rd =  new Random();

        int index = Math.abs(rd.nextInt(rainbow_colorList.length)%rainbow_colorList.length);
        int secondIndex = Math.abs((int)(((long)randomIndex.get(index)+System.currentTimeMillis())%rainbow_colorList.length));

        android.util.Log.i("color","  颜色 index = "+ index + " secondIndex = "+ secondIndex + "  rainbow_colorList.length=  "+rainbow_colorList.length);
        return rainbow_colorList[secondIndex];

    }
    static int[] rainbow_colorList = {
            R.color.MediumOrchid,
            R.color.Black,
            R.color.DarkSeaGreen,
            R.color.Sienna,
            R.color.LightCoral,
            R.color.DarkGrey,
            R.color.LightYellow1,
            R.color.Wheat3,
            R.color.Wheat4,
            R.color.Wheat1,
            R.color.Beige,
            R.color.Wheat2,
            R.color.LightYellow3,
            R.color.LightYellow2,
            R.color.OliveDrab,
            R.color.LightYellow4,
            R.color.DodgerBlue3,
            R.color.DodgerBlue4,
            R.color.DodgerBlue1,
            R.color.Violet,
            R.color.DodgerBlue2,
            R.color.LtGoldenrodYello,
            R.color.PaleGoldenrod,
            R.color.PowderBlue,
            R.color.Magenta,
            R.color.DarkTurquoise,
            R.color.PeachPuff,
            R.color.LightGray,
            R.color.DarkRed,
            R.color.DarkCyan,
            R.color.PaleVioletRed4,
            R.color.Aquamarine1,
            R.color.Aquamarine4,
            R.color.LawnGreen,
            R.color.PaleVioletRed1,
            R.color.Aquamarine2,
            R.color.PaleVioletRed2,
            R.color.Aquamarine3,
            R.color.PaleVioletRed3,
            R.color.DarkOrange,
            R.color.LightGoldenrod4,
            R.color.LightGoldenrod1,
            R.color.LightGoldenrod2,
            R.color.LightGoldenrod3,
            R.color.Maroon,
            R.color.VioletRed4,
            R.color.VioletRed3,
            R.color.VioletRed2,
            R.color.Plum2,
            R.color.Blue,
            R.color.Plum3,
            R.color.Moccasin,
            R.color.Plum1,
            R.color.Turquoise3,
            R.color.Turquoise4,
            R.color.Turquoise1,
            R.color.Turquoise2,
            R.color.Khaki1,
            R.color.SpringGreen3,
            R.color.Khaki4,
            R.color.Red,
            R.color.SpringGreen2,
            R.color.Khaki2,
            R.color.SpringGreen4,
            R.color.Khaki3,
            R.color.SpringGreen1,
            R.color.Honeydew1,
            R.color.Honeydew2,
            R.color.Honeydew3,
            R.color.Honeydew4,
            R.color.NavajoWhite1,
            R.color.NavajoWhite3,
            R.color.MediumPurple4,
            R.color.NavajoWhite2,
            R.color.MediumPurple3,
            R.color.MediumPurple2,
            R.color.NavajoWhite4,
            R.color.MediumPurple1,
            R.color.Yellow1,
            R.color.Yellow2,
            R.color.Yellow3,
            R.color.LightSteelBlue4,
            R.color.LightSteelBlue3,
            R.color.lavender,
            R.color.SlateBlue2,
            R.color.LightSteelBlue2,
            R.color.SlateBlue1,
            R.color.LightSteelBlue1,
            R.color.Burlywood1,
            R.color.SlateBlue4,
            R.color.Gold,
            R.color.Burlywood2,
            R.color.SlateBlue3,
            R.color.Burlywood3,
            R.color.Burlywood4,
            R.color.Yellow4,
            R.color.LemonChiffon,
            R.color.FloralWhite,
            R.color.NavyBlue,
            R.color.LightGoldenrod,
            R.color.Orange4,
            R.color.Orange3,
            R.color.Orange2,
            R.color.Orange1,
            R.color.Bisque,
            R.color.MediumBlue,
            R.color.BlueViolet,
            R.color.DarkGoldenrod4,
            R.color.DarkGoldenrod3,
            R.color.DarkGoldenrod2,
            R.color.DarkGoldenrod1,
            R.color.IndianRed1,
            R.color.Maroon1,
            R.color.HotPink4,
            R.color.Maroon2,
            R.color.HotPink3,
            R.color.Maroon3,
            R.color.Maroon4,
            R.color.Orchid3,
            R.color.Orchid4,
            R.color.OrangeRed3,
            R.color.IndianRed4,
            R.color.OrangeRed4,
            R.color.IndianRed3,
            R.color.IndianRed2,
            R.color.LavenderBlush2,
            R.color.LavenderBlush1,
            R.color.OrangeRed1,
            R.color.LavenderBlush4,
            R.color.MistyRose1,
            R.color.White,
            R.color.OrangeRed2,
            R.color.LavenderBlush3,
            R.color.MistyRose2,
            R.color.Tan4,
            R.color.Tan3,
            R.color.Purple,
            R.color.Tan2,
            R.color.Orchid1,
            R.color.Tan1,
            R.color.Orchid2,
            R.color.Cornsilk1,
            R.color.Cornsilk2,
            R.color.CadetBlue1,
            R.color.Cornsilk3,
            R.color.CadetBlue2,
            R.color.Cornsilk4,
            R.color.CadetBlue3,
            R.color.HotPink2,
            R.color.MistyRose3,
            R.color.CadetBlue4,
            R.color.HotPink1,
            R.color.MistyRose4,
            R.color.SkyBlue,
            R.color.DarkSlateGray,
            R.color.DimGrey,
            R.color.LightSeaGreen,
            R.color.MediumAquamarine,
            R.color.SandyBrown,
            R.color.Blue1,
            R.color.Firebrick,
            R.color.Blue2,
            R.color.Blue3,
            R.color.DeepSkyBlue,
            R.color.Blue4,
            R.color.Salmon1,
            R.color.Salmon2,
            R.color.MediumPurple,
            R.color.Yellow,
            R.color.Salmon3,
            R.color.Salmon4,
            R.color.DarkSlateGray2,
            R.color.DarkSeaGreen2,
            R.color.DarkSlateGray3,
            R.color.DarkSeaGreen3,
            R.color.DarkSlateGray4,
            R.color.DarkSeaGreen4,
            R.color.DarkSlateGray1,
            R.color.Sienna1,
            R.color.DarkSeaGreen1,
            R.color.Turquoise,
            R.color.Bisque2,
            R.color.Bisque1,
            R.color.Bisque4,
            R.color.Bisque3,
            R.color.LavenderBlush,
            R.color.LightCyan,
            R.color.Sienna2,
            R.color.Sienna3,
            R.color.LightSlateBlue,
            R.color.Sienna4,
            R.color.SlateBlue,
            R.color.Orchid,
            R.color.Thistle1,
            R.color.Thistle2,
            R.color.Snow,
            R.color.Thistle3,
            R.color.Thistle4,
            R.color.Tomato,
            R.color.LightSalmon4,
            R.color.Ivory1,
            R.color.RoyalBlue2,
            R.color.Ivory2,
            R.color.RoyalBlue1,
            R.color.Ivory3,
            R.color.RoyalBlue4,
            R.color.Ivory4,
            R.color.RoyalBlue3,
            R.color.LightSalmon1,
            R.color.Plum,
            R.color.LightSalmon2,
            R.color.LightSalmon3,
            R.color.YellowGreen,
            R.color.MintCream,
            R.color.Burlywood,
            R.color.Plum4,
            R.color.VioletRed1,
            R.color.Azure,
            R.color.LightSkyBlue3,
            R.color.Salmon,
            R.color.LightSkyBlue4,
            R.color.LightSkyBlue1,
            R.color.LightSkyBlue2,
            R.color.BlanchedAlmond,
            R.color.SteelBlue3,
            R.color.SteelBlue4,
            R.color.SteelBlue1,
            R.color.Pink,
            R.color.SteelBlue2,
            R.color.Purple1,
            R.color.Purple2,
            R.color.Pink1,
            R.color.Purple3,
            R.color.Red3,
            R.color.Pink2,
            R.color.Red4,
            R.color.Pink3,
            R.color.Red1,
            R.color.Pink4,
            R.color.Red2,
            R.color.MediumOrchid3,
            R.color.MediumOrchid2,
            R.color.MediumOrchid1,
            R.color.Purple4,
            R.color.MediumOrchid4,
            R.color.LightSteelBlue,
            R.color.SteelBlue,
            R.color.PaleTurquoise,
            R.color.DarkGoldenrod,
            R.color.DeepPink,
            R.color.MediumVioletRed,
            R.color.SlateGray4,
            R.color.SaddleBrown,
            R.color.SlateGray2,
            R.color.SlateGray3,
            R.color.SlateGray1,
            R.color.DarkOrange1,
            R.color.DarkOrange3,
            R.color.DarkOrange2,
            R.color.Gainsboro,
            R.color.DodgerBlue,
            R.color.SkyBlue4,
            R.color.Aquamarine,
            R.color.SkyBlue3,
            R.color.PeachPuff2,
            R.color.DarkOrchid4,
            R.color.DarkOrange4,
            R.color.PeachPuff3,
            R.color.DarkOrchid3,
            R.color.PeachPuff4,
            R.color.DarkOrchid2,
            R.color.DarkOrchid1,
            R.color.MedSpringGreen,
            R.color.SkyBlue2,
            R.color.SkyBlue1,
            R.color.PeachPuff1,
            R.color.LimeGreen,
            R.color.Snow2,
            R.color.Snow1,
            R.color.Green4,
            R.color.Green3,
            R.color.IndianRed,
            R.color.Green2,
            R.color.Green1,
            R.color.Snow4,
            R.color.Snow3,
            R.color.LightBlue,
            R.color.SpringGreen,
            R.color.Wheat,
            R.color.SeaGreen4,
            R.color.LemonChiffon4,
            R.color.LemonChiffon1,
            R.color.LemonChiffon3,
            R.color.LemonChiffon2,
            R.color.RosyBrown1,
            R.color.RosyBrown2,
            R.color.Goldenrod3,
            R.color.Goldenrod2,
            R.color.Goldenrod4,
            R.color.Tomato1,
            R.color.Goldenrod1,
            R.color.RosyBrown3,
            R.color.RosyBrown4,
            R.color.Chocolate,
            R.color.Tomato4,
            R.color.Tomato3,
            R.color.Tomato2,
            R.color.SeaGreen,
            R.color.Thistle,
            R.color.MistyRose,
            R.color.Azure2,
            R.color.Azure1,
            R.color.SeaGreen1,
            R.color.Azure4,
            R.color.Azure3,
            R.color.SeaGreen3,
            R.color.SeaGreen2,
            R.color.DarkBlue,
            R.color.gray91,
            R.color.Cornsilk,
            R.color.PaleGreen,
            R.color.DarkOliveGreen,
            R.color.AntiqueWhite4,
            R.color.Cyan1,
            R.color.AntiqueWhite2,
            R.color.Cyan2,
            R.color.AntiqueWhite3,
            R.color.AntiqueWhite1,
            R.color.gray81,
            R.color.GreenYellow,
            R.color.Ivory,
            R.color.LightSkyBlue,
            R.color.OliveDrab1,
            R.color.DarkGreen,
            R.color.Cyan3,
            R.color.OliveDrab2,
            R.color.DarkSalmon,
            R.color.Cyan4,
            R.color.OliveDrab3,
            R.color.Linen,
            R.color.OliveDrab4,
            R.color.LightGreen,
            R.color.LightCyan4,
            R.color.Brown,
            R.color.Brown1,
            R.color.LightCyan3,
            R.color.LightCyan2,
            R.color.LightCyan1,
            R.color.Brown4,
            R.color.Brown2,
            R.color.Brown3,
            R.color.CornflowerBlue,
            R.color.Grey,
            R.color.DarkKhaki,
            R.color.Coral3,
            R.color.Coral4,
            R.color.Coral1,
            R.color.Coral2,
            R.color.ForestGreen,
            R.color.DarkOrchid,
            R.color.DarkMagenta,
            R.color.Green,
            R.color.LightBlue4,
            R.color.LightBlue3,
            R.color.LightBlue2,
            R.color.grey11,
            R.color.LightBlue1,
            R.color.LightSlateGray,
            R.color.Orange,
            R.color.Firebrick1,
            R.color.Firebrick2,
            R.color.RoyalBlue,
            R.color.DarkViolet,
            R.color.DarkOliveGreen1,
            R.color.MediumSlateBlue,
            R.color.DarkOliveGreen3,
            R.color.Firebrick3,
            R.color.DarkOliveGreen2,
            R.color.Firebrick4,
            R.color.DarkOliveGreen4,
            R.color.MidnightBlue,
            R.color.PaleGreen4,
            R.color.PaleGreen3,
            R.color.PaleGreen2,
            R.color.PaleGreen1,
            R.color.DarkSlateBlue,
            R.color.Chartreuse,
            R.color.Peru,
            R.color.RosyBrown,
            R.color.PaleTurquoise2,
            R.color.DeepPink3,
            R.color.PaleTurquoise1,
            R.color.DeepPink2,
            R.color.DeepSkyBlue1,
            R.color.DeepPink4,
            R.color.DeepSkyBlue2,
            R.color.DeepSkyBlue3,
            R.color.grey31,
            R.color.DeepSkyBlue4,
            R.color.PaleTurquoise4,
            R.color.PaleTurquoise3,
            R.color.VioletRed,
            R.color.OrangeRed,
            R.color.DeepPink1,
            R.color.Cyan,
            R.color.grey21,
            R.color.WhiteSmoke,
            R.color.MediumSeaGreen,
            R.color.NavajoWhite,
            R.color.Tan,
            R.color.LightSalmon,
            R.color.grey51,
            R.color.Seashell,
            R.color.Seashell2,
            R.color.Seashell1,
            R.color.Seashell4,
            R.color.PaleVioletRed,
            R.color.Seashell3,
            R.color.Chocolate4,
            R.color.LightPink4,
            R.color.grey41,
            R.color.Gold4,
            R.color.Chocolate2,
            R.color.LightPink3,
            R.color.Gold1,
            R.color.goldenrod,
            R.color.Chocolate3,
            R.color.LightPink2,
            R.color.Gold2,
            R.color.LightPink1,
            R.color.Gold3,
            R.color.Chocolate1,
            R.color.Magenta2,
            R.color.Magenta1,
            R.color.AliceBlue,
            R.color.Magenta4,
            R.color.Magenta3,
            R.color.PapayaWhip,
            R.color.Honeydew,
            R.color.MediumTurquoise,
            R.color.AntiqueWhite,
            R.color.grey71,
            R.color.OldLace,
            R.color.LightPink,
            R.color.CadetBlue,
            R.color.GhostWhite,
            R.color.grey61,
            R.color.HotPink,
            R.color.LightYellow,
            R.color.Coral,
            R.color.SlateGrey,
            R.color.Chartreuse4,
            R.color.Chartreuse2,
            R.color.Chartreuse3,
            R.color.Chartreuse1
    };


}
